### ISSUE TITLE
no clear instructions on how to use any other model 

### ISSUE THREAD

**Issue by aertist** [gordicaleksa/pytorch-deepdream#6]
`!python deepdream.py --input pink.jpg --img_width 2000 --num_gradient_ascent_iterations 10 --pyramid_size 4 --pyramid_ratio 1.2 --smoothing_coefficient 0.5 --model SupportedModels=0 --pretrained_weights IMAGNET`

usage: deepdream.py [-h] [--input INPUT] [--img_width IMG_WIDTH]
                    [--model {SupportedModels.VGG16,SupportedModels.VGG16_EXPERIMENTAL,SupportedModels.GOOGLENET,SupportedModels.RESNET50,SupportedModels.ALEXNET}]
                    [--pretrained_weights {SupportedPretrainedWeights.IMAGENET,SupportedPretrainedWeights.PLACES_365}]
                    [--layers_to_use LAYERS_TO_USE]
                    [--pyramid_size PYRAMID_SIZE]
                    [--pyramid_ratio PYRAMID_RATIO]
                    [--num_gradient_ascent_iterations NUM_GRADIENT_ASCENT_ITERATIONS]
                    [--lr LR] [--is_video IS_VIDEO]
                    [--video_length VIDEO_LENGTH]
                    [--frame_transform {SupportedTransforms.ZOOM,SupportedTransforms.ZOOM_ROTATE,SupportedTransforms.TRANSLATE}]
                    [--blend BLEND] [--should_display SHOULD_DISPLAY]
                    [--spatial_shift_size SPATIAL_SHIFT_SIZE]
                    [--smoothing_coefficient SMOOTHING_COEFFICIENT]
                    [--use_noise USE_NOISE]
deepdream.py: error: argument --model: invalid choice: 'SupportedModels=0' (choose from <SupportedModels.VGG16: 0>, <SupportedModels.VGG16_EXPERIMENTAL: 1>, <SupportedModels.GOOGLENET: 2>, <SupportedModels.RESNET50: 3>, <SupportedModels.ALEXNET: 4>)

what am i doing wrong?? 😞😪

**Comment by aertist** [comment]
respond please

**Comment by Hoversquid** [comment]
I'm having trouble selecting another model through the command line.
You can do it through the deepdream.py file by setting the default to something like:
`parser.add_argument("--model", choices=SupportedModels, help="Neural network (model) to use for dreaming", default=SupportedModels.RESNET50)`
I'd really like some clarification about how to use this in the command line, because I'm really enjoying this code but changing the python script is tedious. Thanks :)

**Comment by gordicaleksa** [comment]
Unfortunately, I haven't designed it with the command line as the first-class citizen but it's a super fast fix.

I'll add the jupyter notebook and make it easy to use via command line this weekend. Stay tuned.

**Comment by Hoversquid** [comment]
This is an amazing project, thanks for continuing to add to it!

**Comment by gordicaleksa** [comment]
Hey guys!

The project just went through some serious refactoring and I've added new features as well:
* it's now completely command-line friendly (I tested it myself)
* I've added a Jupyter Notebook which is probably THE BEST place to start
* I've refactored many functions and added additional explanations and comments

Please pull the newest changes, test them and let me know how it went!

If everything's ok I'm closing this issue.

**Comment by reillydonovan** [comment]
Can you provide a command line example where you are changing all input parameters to something other than the default?
